[package]
name = "fluent-ai-simd"
version = "0.1.0"
edition = "2024"
description = "Shared high-performance SIMD operations for fluent-ai ecosystem"
authors = ["Fluent AI Contributors"]
license = "MIT"
repository = "https://github.com/cyrusnimda/fluent-ai"

[dependencies]
# Core SIMD support and zero-allocation data structures
wide = "0.7"
arrayvec = "0.7"
smallvec = "2.0.0-alpha.11"

# Hash map for token tracking and statistics
dashmap = "6.1"
ahash = "0.8"

# Atomic operations and synchronization
parking_lot = "0.12"
crossbeam-utils = "0.8"

# Random number generation for sampling
rand = "0.8"

# Fast exponential functions for softmax
libm = "0.2"

# Error handling
thiserror = "2.0.12"

# Lazy static initialization for runtime dispatch
once_cell = "1.21.3"
lazy_static = "1.5"

# Optional candle integration
candle-core = { git = "https://github.com/huggingface/candle", branch = "main", default-features = false, optional = true }

# Workspace hack for unified dependency resolution
fluent-ai-workspace-hack = { path = "../../workspace-hack" }

[features]
default = []
candle = ["dep:candle-core"]
portable_simd = []

[dev-dependencies]
criterion = "0.5"
approx = "0.5"
float_eq = "1.0"
