[package]
name = "fluent_ai_http3"
version = "0.1.0"
edition = "2024"
description = "Zero-allocation HTTP/3 (QUIC) client with HTTP/2 fallback for AI providers"
license = "MIT"
repository = "https://github.com/cyrup-ai/fluent-ai"
keywords = ["http3", "quic", "ai", "zero-allocation", "blazing-fast"]
categories = ["network-programming", "web-programming::http-client"]

[dependencies]
fluent-ai-workspace-hack = { path = "../../workspace-hack" }
fluent_ai_async = { package = "fluent_ai_async", path = "../async-stream" }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = { version = "1.0.142", optional = true }
serde_urlencoded = "0.7.1"
thiserror = "2.0.12"
hashbrown = { version = "0.15.4", features = ["serde"] }
http = "1.3.1"
once_cell = { version = "1.21.3", optional = true }
tracing = "0.1.41"
bytes = "1.10.1"
pin-project-lite = "0.2.16"
fastrand = "2.3.0"
url = "2.5.4"
crossbeam = "0.8.4"
crossbeam-skiplist = "0.1.3"
chrono = { version = "0.4.41", features = ["serde"] }
base64 = "0.22.1"
crossbeam-queue = "0.3.12"
crossbeam-channel = "0.5.15"
lazy_static = "1.5.0"
urlencoding = "2.1.3"
log = "0.4.27"
regex = "1.11.1"
libc = "0.2.174"
cyrup_sugars = { git = "https://github.com/cyrup-ai/cyrup-sugars", branch = "main", package = "cyrup_sugars", features = ["all"] }
futures-executor = "0.3.31" # Pure AsyncStream architecture
sync_wrapper = { version = "1.0", features = ["futures"] }
mime_guess = { version = "2.0", default-features = false, optional = true }
arrayvec = "0.7.6"
smallvec = "1.15.1"
heapless = "0.8.0"
crossbeam-utils = "0.8.21"
cache-padded = "1.3.0"
atomic = "0.6.1"
futures = "0.3.31"
hyper-util = { version = "0.1", features = ["http1", "http2", "client", "client-legacy"] }
hickory-resolver = { version = "0.25", optional = true }
quinn = { version = "0.11", features = ["rustls"], optional = true }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
encoding_rs = { version = "0.8", optional = true }
http-body = "1"
http-body-util = "0.1"
hyper = { version = "1.6.0", features = ["http1", "client"] }
hyper-util = { version = "0.1", features = ["http1", "http2", "client", "client-legacy", "tokio"] }
h2 = { version = "0.4", optional = true }
percent-encoding = "2.3.1"
rustls-pki-types = { version = "1.12.0", features = ["std"], optional = true }
mime = { version = "0.3.17", optional = true }
hyper-tls = { version = "0.6", optional = true }
native-tls-crate = { version = "0.2", optional = true, package = "native-tls" }
hyper-rustls = { version = "0.27", default-features = false, optional = true, features = ["http1", "tls12"] }
rustls = { version = "0.23", optional = true, default-features = false, features = ["std", "tls12"] }
webpki-roots = { version = "1", optional = true }
rustls-native-certs = { version = "0.8", optional = true }
cookie_crate = { version = "0.18.1", package = "cookie", optional = true }
cookie_store = { version = "0.22.0", optional = true }
hickory-resolver = { version = "0.25", optional = true, features = ["tokio"] }
h3 = { version = "0.0.8", optional = true }
h3-quinn = { version = "0.0.10", optional = true }
quinn = { version = "0.11", default-features = false, features = ["rustls", "runtime-tokio"], optional = true }
flate2 = { version = "1.1.2", optional = true }
brotli_crate = { package = "brotli", version = "8.0.1", optional = true }
zstd_crate = { package = "zstd", version = "0.13.3", optional = true }

[target.'cfg(not(target_arch = "wasm32"))'.dev-dependencies]
env_logger = "0.11.8"
hyper = { version = "1.6.0", default-features = false, features = ["http1", "http2", "client", "server"] }
hyper-util = { version = "0.1", features = ["http1", "http2", "client", "client-legacy", "server-auto", "server-graceful", "tokio"] }
serde = { version = "1.0.219", features = ["derive"] }
flate2 = "1.1.2"
brotli_crate = { package = "brotli", version = "8.0.1" }
zstd_crate = { package = "zstd", version = "0.13.3" }
doc-comment = "0.3"
# futures-util = { version = "0.3.31", default-features = false, features = ["std", "alloc"] }

[target.'cfg(target_arch = "wasm32")'.dependencies]
js-sys = "0.3.77"
serde_json = "1.0.142"
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
wasm-streams = { version = "0.4", optional = true }

[target.'cfg(target_arch = "wasm32")'.dependencies.web-sys]
version = "0.3"
features = [
    "AbortController",
    "AbortSignal",
    "Headers",
    "Request",
    "RequestInit",
    "RequestMode",
    "Response",
    "Window",
    "FormData",
    "Blob",
    "BlobPropertyBag",
    "ServiceWorkerGlobalScope",
    "RequestCredentials",
    "File",
    "ReadableStream",
    "RequestCache"
]

[target.'cfg(target_arch = "wasm32")'.dev-dependencies]
wasm-bindgen = { version = "0.2", features = ["serde-serialize"] }
wasm-bindgen-test = "0.3"

[dev-dependencies]
env_logger = "0.11.8"
axum = "0.8.4"
chrono = { version = "0.4.41", features = ["serde"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.142"
criterion = { version = "0.7.0", features = ["html_reports"] }
jemallocator = "0.5.4"
dhat = "0.3.3"
tower = { version = "0.5.2", default-features = false, features = ["limit"] }
num_cpus = "1.17.0"
libc = "0.2.174"

[lib]
name = "fluent_ai_http3"
path = "src/lib.rs"

[[bench]]
name = "performance_suite"
harness = false

[features]
default = ["http3", "connection-pool", "compression", "http3_unstable", "default-tls", "charset", "http2", "system-proxy", "json", "stream", "rustls-tls", "rustls-tls-native-roots", "rustls-tls-manual-roots", "gzip", "deflate", "brotli"]
http3 = ["rustls-tls-manual-roots", "dep:h3", "dep:h3-quinn", "dep:quinn"]
connection-pool = []
compression = []
http3_unstable = []
default-tls = ["dep:hyper-tls", "dep:native-tls-crate", "__tls"]
http2 = ["h2", "hyper/http2", "hyper-util/http2", "hyper-rustls?/http2"]
native-tls = ["default-tls"]
native-tls-alpn = ["native-tls", "native-tls-crate?/alpn", "hyper-tls?/alpn"]
native-tls-vendored = ["native-tls", "native-tls-crate?/vendored"]
rustls-tls = ["rustls-tls-webpki-roots"]
rustls-tls-no-provider = ["rustls-tls-manual-roots-no-provider"]
rustls-tls-manual-roots-no-provider = ["__rustls"]
rustls-tls-webpki-roots-no-provider = ["dep:webpki-roots", "hyper-rustls?/webpki-tokio", "__rustls"]
rustls-tls-native-roots-no-provider = ["dep:rustls-native-certs", "hyper-rustls?/native-tokio", "__rustls"]
rustls-tls-manual-roots = ["rustls-tls-manual-roots-no-provider", "__rustls-ring"]
rustls-tls-webpki-roots = ["rustls-tls-webpki-roots-no-provider", "__rustls-ring"]
rustls-tls-native-roots = ["rustls-tls-native-roots-no-provider", "__rustls-ring"]

charset = ["dep:encoding_rs", "dep:mime"]
cookies = ["dep:cookie_crate", "dep:cookie_store"]
gzip = ["dep:flate2"]
brotli = ["dep:brotli_crate"]
zstd = ["dep:zstd_crate"]
deflate = ["dep:flate2"]
json = ["dep:serde_json"]
multipart = ["dep:mime_guess"]
trust-dns = []
hickory-dns = ["dep:hickory-resolver", "dep:once_cell"]
stream = ["dep:wasm-streams"]
socks = []
system-proxy = ["hyper-util/client-proxy-system"]
macos-system-configuration = ["system-proxy"]
__tls = ["dep:rustls-pki-types"]
__rustls = ["dep:hyper-rustls", "dep:rustls", "__tls"]
__rustls-ring = ["hyper-rustls?/ring", "rustls?/ring", "quinn?/ring"]

[[example]]
name = "fluent_builder"
test = false
