[package]
name = "fluent_ai_http3"
version = "0.1.0"
edition = "2024"
description = "Zero-allocation HTTP/3 (QUIC) client with HTTP/2 fallback for AI providers"
license = "MIT"
repository = "https://github.com/cyrup-ai/fluent-ai"
keywords = ["http3", "quic", "ai", "zero-allocation", "blazing-fast"]
categories = ["network-programming", "web-programming::http-client"]

[dependencies]
fluent-ai-workspace-hack = { path = "../../workspace-hack" }
fluent_ai_async = { package = "fluent_ai_async", version = "0.1.0", path = "../async-stream" }
reqwest = { version = "0.12.22", features = ["json", "stream", "http3", "rustls-tls", "rustls-tls-native-roots", "rustls-tls-manual-roots", "gzip", "deflate", "brotli"] }
tokio = { version = "1.47.0", features = ["full"] }
tokio-stream = "0.1.17"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.141"
serde_urlencoded = "0.7.1"
thiserror = "2.0.12"
futures = "0.3.31"
hashbrown = { version = "0.15.4", features = ["serde"] }
http = "1.3.1"
once_cell = "1.21.3"
tracing = "0.1.41"
bytes = "1.10.1"
pin-project-lite = "0.2.16"
fastrand = "2.3.0"
url = "2.5.4"
crossbeam = "0.8.4"
crossbeam-skiplist = "0.1.3"
chrono = { version = "0.4.41", features = ["serde"] }
async-stream = "0.3.6"
cyrup_sugars = { git = "https://github.com/cyrup-ai/cyrup-sugars", package = "cyrup_sugars", branch = "main", features = ["all"] }
sugars_macros = { git = "https://github.com/cyrup-ai/cyrup-sugars", package = "sugars_macros", branch = "main" }
base64 = "0.22.1"
crossbeam-queue = "0.3.12"
crossbeam-channel = "0.5.15"
futures-util = "0.3.31"
lazy_static = "1.5.0"
urlencoding = "2.1.3"
log = "0.4.27"

[dev-dependencies]
env_logger = "0.11.8"
futures-util = "0.3.31"
tokio = { version = "1.47.0", features = ["full"] }
axum = "0.8.4"

[lib]
name = "fluent_ai_http3"
path = "src/lib.rs"

[features]
default = ["http3", "connection-pool", "compression"]
http3 = []
connection-pool = []
compression = []
