[package]
name = "test-template"
version = "0.1.0"
edition = "2021"

[dependencies]
cyrup_sugars = { path = "../packages/cyrup-sugars", features = ["tokio-async"] }
tokio = { version = "1.0", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"