[template]
cargo_generate_version = ">=0.10.0"

[placeholders.project-name]
type = "string"
prompt = "Project name"
regex = "^[a-zA-Z][a-zA-Z0-9_-]*$"

[placeholders.features]
type = "string"
prompt = "Cyrup Sugars features (comma-separated)"
default = "tokio-async"
choices = ["tokio-async", "std-async", "crossbeam-async", "hashbrown-json", "all"]

[placeholders.include_examples]
type = "bool"
prompt = "Include example code?"
default = true

[placeholders.author]
type = "string"
prompt = "Author name"
default = "{{ authors }}"

[placeholders.description]
type = "string"
prompt = "Project description"
default = "A project using cyrup-sugars"

[conditional.'include_examples == false']
ignore = [
    "examples/**/*"
]