[workspace]
resolver = "3"
members = [
    "packages/fluent-ai",
    "packages/provider",
    "packages/domain", 
    "packages/memory",
    "packages/http3",
    "packages/cylo",
    "packages/termcolor",

    "packages/fluent-ai-candle",
    "workspace-hack"
]
exclude = ["tmp/rig", "tmp/cyrup-agent", "tmp/cyrup-sugars", "tmp/candle"]

[patch.crates-io]
candle-core = { git = "https://github.com/huggingface/candle" }
candle-nn = { git = "https://github.com/huggingface/candle" }
candle-transformers = { git = "https://github.com/huggingface/candle" }

[workspace.dependencies]
half = { version = "2.6.0", features = ["serde", "num-traits", "bytemuck", "zerocopy", "rand_distr"] }

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "MIT"
authors = ["CYRUP AI"]
repository = "https://github.com/cyrup-ai/fluent-ai"

