[workspace]
resolver = "3"
members = [
    "packages/fluent-ai",
    "packages/provider",
    "packages/domain", 
    "packages/http3",
    "packages/cylo",
    "packages/termcolor",
    "packages/memory"
]
exclude = ["tmp/rig", "tmp/cyrup-agent", "tmp/cyrup-sugars", "tmp/candle"]

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "MIT"
authors = ["CYRUP AI"]
repository = "https://github.com/cyrup-ai/fluent-ai"

[workspace.dependencies]
anyhow = "1.0.98"
serde = { version = "1.0.219", features = ["derive"] }
tracing = "0.1.41"
thiserror = "2.0.12"
clap = "4.5.41"
tracing-subscriber = "0.3.19"
tempfile = "3.20.0"
chrono = "0.4.41"
uuid = "1.17.0"
tokio = "1.46.1"
statig = "0.4.1"
watchexec = "8.0.1"
watchexec-events = "6.0.0"
watchexec-signals = "5.0.0"
xattr = "1.5.1"
assert_fs = "1.1.3"
assert_cmd = "2.0.17"
predicates = "3.1.3"

