[package]
name = "fluent-ai-rig"
version = "0.1.0"
edition = "2021"

[lib]
name = "fluent_ai_rig"
path = "src/lib.rs"

[[bin]]
name = "fluent_ai_rig"
path = "src/main.rs"

[dependencies]
clap = { version = "4.5.29", features = ["derive"] }
fluent-ai = { version = "0.1.0", path = "../fluent-ai" }
fluent_ai_provider = { version = "0.1.0", path = "../provider" }
futures = "0.3.30"
rig-core = { git = "https://github.com/0xPlaygrounds/rig.git", branch = "main", features = ["all", "mcp", "reqwest-rustls", "audio", "image", "worker"] }
rig-surrealdb = { git = "https://github.com/0xPlaygrounds/rig.git", branch = "main" }
serde = "1.0.219"
serde_json = "1.0.140"
tokio = { version = "1.46.1", features = ["full"] }
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
# workspace-hack = { version = "0.1", path = "../../../workspace-hack" }
