# HTTP3 package specific Cargo configuration
# Enables reqwest_unstable for full QUIC optimization

[build]
# Enable reqwest_unstable for HTTP/3 QUIC features
rustflags = ["--cfg", "reqwest_unstable"]

[env]
# Set environment variable for HTTP/3 package
REQWEST_UNSTABLE = "1"