[package]
name = "model-info"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
description = "Dynamic retrieval and structured representation of AI model info from various providers using build-time code generation for strongly typed enums"

[dependencies]
fluent_ai_http3 = { path = "../http3" }
fluent-ai-async = { path = "../fluent-ai-async" }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.141"
anyhow = "1.0.95"
tokio = { version = "1.46.1", features = ["rt", "macros"] }
hashbrown = "0.15.4"
http = "1.2.0"

[build-dependencies]
fluent_ai_http3 = { path = "../http3" }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.141"
quote = "1.0.38"
syn = { version = "2.0.90", features = ["full"] }
proc-macro2 = "1.0.92"
anyhow = "1.0.95"
hashbrown = "0.15.4"
tokio = { version = "1.46.1", features = ["rt", "macros"] }
