[package]
name = "model-info"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
description = "Dynamic retrieval and structured representation of AI model info from various providers using build-time code generation for strongly typed enums"

[features]
default = ["reqwest_unstable"]
reqwest_unstable = []

[dependencies]
fluent_ai_http3 = { path = "../http3" }
fluent_ai_async = { path = "../async-stream" }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.141"
anyhow = "1.0.98"
tokio = { version = "1.47.0", features = ["rt", "macros"] }
hashbrown = "0.15.4"
http = "1.3.1"
thiserror = "2.0.12"
ahash = "0.8.12"
dashmap = "6.1.0"
once_cell = "1.21.3"
arrayvec = "0.7.6"
parking_lot = "0.12.4"
smallvec = "2.0.0-alpha.11"
cyrup_sugars = { git = "https://github.com/cyrup-ai/cyrup-sugars", branch = "main", package = "cyrup_sugars", features = ["all"] }
reqwest = { version = "0.12.22", features = ["json", "stream", "http3", "rustls-tls", "rustls-tls-native-roots", "rustls-tls-manual-roots", "gzip", "deflate", "brotli"] }


[build-dependencies]
fluent_ai_http3 = { path = "../http3" }
fluent_ai_async = { path = "../async-stream" }
termcolor = { path = "../termcolor" }
reqwest = { version = "0.12.22", features = ["json", "stream", "http3", "rustls-tls", "rustls-tls-native-roots", "rustls-tls-manual-roots", "gzip", "deflate", "brotli"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.141"
quote = "1.0.40"
syn = { version = "2.0.104", features = ["full", "extra-traits", "parsing", "printing"] }
proc-macro2 = "1.0.95"
anyhow = "1.0.98"
hashbrown = "0.15.4"
tokio = { version = "1.47.0", features = ["rt", "macros"] }
prettyplease = "0.2.36"
chrono = { version = "0.4.41", features = ["serde"] }
dashmap = "6.1"
once_cell = "1.21.3"
http = "1.3.1"
cyrup_sugars = { git = "https://github.com/cyrup-ai/cyrup-sugars", branch = "main", package = "cyrup_sugars", features = ["all"] }
