#![doc = r" Generated provider implementation from AiChat models.yaml"]
#![doc = r""]
#![doc = r" This file is auto-generated. Do not edit manually."]
#![doc = r" Generated from: https://github.com/sigoden/aichat/blob/main/models.yaml"]
use crate::{model::Models, Model, Provider};
use serde::{Deserialize, Serialize};
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum Providers {
    Openai,
    Gemini,
    Claude,
    Mistral,
    Ai21,
    Cohere,
    Xai,
    Perplexity,
    Groq,
    Vertexai,
    Bedrock,
    Cloudflare,
    Ernie,
    Qianwen,
    Hunyuan,
    Moonshot,
    Deepseek,
    Zhipuai,
    Minimax,
    Openrouter,
    Github,
    Deepinfra,
    Jina,
    Voyageai,
}
impl Provider for Providers {
    fn models(&self) -> Vec<Box<dyn Model>> {
        match self {
            Providers::Openai => vec![
                Box::new(Models::OpenaiGpt41) as Box<dyn Model>,
                Box::new(Models::OpenaiGpt41Mini) as Box<dyn Model>,
                Box::new(Models::OpenaiGpt41Nano) as Box<dyn Model>,
                Box::new(Models::OpenaiGpt4o) as Box<dyn Model>,
                Box::new(Models::OpenaiGpt4oSearchPreview) as Box<dyn Model>,
                Box::new(Models::OpenaiGpt4oMini) as Box<dyn Model>,
                Box::new(Models::OpenaiGpt4oMiniSearchPreview) as Box<dyn Model>,
                Box::new(Models::OpenaiChatgpt4oLatest) as Box<dyn Model>,
                Box::new(Models::OpenaiO4Mini) as Box<dyn Model>,
                Box::new(Models::OpenaiO4MiniHigh) as Box<dyn Model>,
                Box::new(Models::OpenaiO3) as Box<dyn Model>,
                Box::new(Models::OpenaiO3Mini) as Box<dyn Model>,
                Box::new(Models::OpenaiO3MiniHigh) as Box<dyn Model>,
                Box::new(Models::OpenaiGpt4Turbo) as Box<dyn Model>,
                Box::new(Models::OpenaiGpt35Turbo) as Box<dyn Model>,
                Box::new(Models::OpenaiTextEmbedding3Large) as Box<dyn Model>,
                Box::new(Models::OpenaiTextEmbedding3Small) as Box<dyn Model>,
            ],
            Providers::Gemini => vec![
                Box::new(Models::GeminiGemini25Flash) as Box<dyn Model>,
                Box::new(Models::GeminiGemini25Pro) as Box<dyn Model>,
                Box::new(Models::GeminiGemini25FlashLitePreview0617) as Box<dyn Model>,
                Box::new(Models::GeminiGemini20Flash) as Box<dyn Model>,
                Box::new(Models::GeminiGemini20FlashLite) as Box<dyn Model>,
                Box::new(Models::GeminiGemma327bIt) as Box<dyn Model>,
                Box::new(Models::GeminiTextEmbedding004) as Box<dyn Model>,
            ],
            Providers::Claude => vec![
                Box::new(Models::ClaudeClaudeOpus420250514) as Box<dyn Model>,
                Box::new(Models::ClaudeClaudeOpus420250514Thinking) as Box<dyn Model>,
                Box::new(Models::ClaudeClaudeSonnet420250514) as Box<dyn Model>,
                Box::new(Models::ClaudeClaudeSonnet420250514Thinking) as Box<dyn Model>,
                Box::new(Models::ClaudeClaude37Sonnet20250219) as Box<dyn Model>,
                Box::new(Models::ClaudeClaude37Sonnet20250219Thinking) as Box<dyn Model>,
                Box::new(Models::ClaudeClaude35Sonnet20241022) as Box<dyn Model>,
                Box::new(Models::ClaudeClaude35Haiku20241022) as Box<dyn Model>,
            ],
            Providers::Mistral => vec![
                Box::new(Models::MistralMistralMediumLatest) as Box<dyn Model>,
                Box::new(Models::MistralMistralSmallLatest) as Box<dyn Model>,
                Box::new(Models::MistralMagistralMediumLatest) as Box<dyn Model>,
                Box::new(Models::MistralMagistralSmallLatest) as Box<dyn Model>,
                Box::new(Models::MistralDevstralSmallLatest) as Box<dyn Model>,
                Box::new(Models::MistralCodestralLatest) as Box<dyn Model>,
                Box::new(Models::MistralMistralEmbed) as Box<dyn Model>,
            ],
            Providers::Ai21 => vec![
                Box::new(Models::Ai21JambaLarge) as Box<dyn Model>,
                Box::new(Models::Ai21JambaMini) as Box<dyn Model>,
            ],
            Providers::Cohere => vec![
                Box::new(Models::CohereCommandA032025) as Box<dyn Model>,
                Box::new(Models::CohereCommandR7b122024) as Box<dyn Model>,
                Box::new(Models::CohereEmbedV40) as Box<dyn Model>,
                Box::new(Models::CohereEmbedEnglishV30) as Box<dyn Model>,
                Box::new(Models::CohereEmbedMultilingualV30) as Box<dyn Model>,
                Box::new(Models::CohereRerankV35) as Box<dyn Model>,
                Box::new(Models::CohereRerankEnglishV30) as Box<dyn Model>,
                Box::new(Models::CohereRerankMultilingualV30) as Box<dyn Model>,
            ],
            Providers::Xai => vec![
                Box::new(Models::XaiGrok3Latest) as Box<dyn Model>,
                Box::new(Models::XaiGrok3FastLatest) as Box<dyn Model>,
                Box::new(Models::XaiGrok3MiniLatest) as Box<dyn Model>,
                Box::new(Models::XaiGrok3MiniFastLatest) as Box<dyn Model>,
            ],
            Providers::Perplexity => vec![
                Box::new(Models::PerplexitySonarPro) as Box<dyn Model>,
                Box::new(Models::PerplexitySonar) as Box<dyn Model>,
                Box::new(Models::PerplexitySonarReasoningPro) as Box<dyn Model>,
                Box::new(Models::PerplexitySonarReasoning) as Box<dyn Model>,
                Box::new(Models::PerplexitySonarDeepResearch) as Box<dyn Model>,
                Box::new(Models::PerplexityR11776) as Box<dyn Model>,
            ],
            Providers::Groq => vec![
                Box::new(Models::GroqMetaLlamaLlama4Maverick17b128eInstruct) as Box<dyn Model>,
                Box::new(Models::GroqMetaLlamaLlama4Scout17b16eInstruct) as Box<dyn Model>,
                Box::new(Models::GroqLlama3370bVersatile) as Box<dyn Model>,
                Box::new(Models::GroqQwenQwq32b) as Box<dyn Model>,
                Box::new(Models::GroqQwenQwen332b) as Box<dyn Model>,
            ],
            Providers::Vertexai => vec![
                Box::new(Models::VertexaiGemini25Flash) as Box<dyn Model>,
                Box::new(Models::VertexaiGemini25Pro) as Box<dyn Model>,
                Box::new(Models::VertexaiGemini25FlashLitePreview0617) as Box<dyn Model>,
                Box::new(Models::VertexaiGemini20Flash001) as Box<dyn Model>,
                Box::new(Models::VertexaiGemini20FlashLite001) as Box<dyn Model>,
                Box::new(Models::VertexaiClaudeOpus420250514) as Box<dyn Model>,
                Box::new(Models::VertexaiClaudeOpus420250514Thinking) as Box<dyn Model>,
                Box::new(Models::VertexaiClaudeSonnet420250514) as Box<dyn Model>,
                Box::new(Models::VertexaiClaudeSonnet420250514Thinking) as Box<dyn Model>,
                Box::new(Models::VertexaiClaude37Sonnet20250219) as Box<dyn Model>,
                Box::new(Models::VertexaiClaude37Sonnet20250219Thinking) as Box<dyn Model>,
                Box::new(Models::VertexaiClaude35SonnetV220241022) as Box<dyn Model>,
                Box::new(Models::VertexaiClaude35Haiku20241022) as Box<dyn Model>,
                Box::new(Models::VertexaiMistralSmall2503) as Box<dyn Model>,
                Box::new(Models::VertexaiCodestral2501) as Box<dyn Model>,
                Box::new(Models::VertexaiTextEmbedding005) as Box<dyn Model>,
                Box::new(Models::VertexaiTextMultilingualEmbedding002) as Box<dyn Model>,
            ],
            Providers::Bedrock => vec![
                Box::new(Models::BedrockUsAnthropicClaudeOpus420250514V10) as Box<dyn Model>,
                Box::new(Models::BedrockUsAnthropicClaudeOpus420250514V10Thinking)
                    as Box<dyn Model>,
                Box::new(Models::BedrockUsAnthropicClaudeSonnet420250514V10) as Box<dyn Model>,
                Box::new(Models::BedrockUsAnthropicClaudeSonnet420250514V10Thinking)
                    as Box<dyn Model>,
                Box::new(Models::BedrockUsAnthropicClaude37Sonnet20250219V10) as Box<dyn Model>,
                Box::new(Models::BedrockUsAnthropicClaude37Sonnet20250219V10Thinking)
                    as Box<dyn Model>,
                Box::new(Models::BedrockAnthropicClaude35Sonnet20241022V20) as Box<dyn Model>,
                Box::new(Models::BedrockAnthropicClaude35Haiku20241022V10) as Box<dyn Model>,
                Box::new(Models::BedrockUsMetaLlama4Maverick17bInstructV10) as Box<dyn Model>,
                Box::new(Models::BedrockUsMetaLlama4Scout17bInstructV10) as Box<dyn Model>,
                Box::new(Models::BedrockUsMetaLlama3370bInstructV10) as Box<dyn Model>,
                Box::new(Models::BedrockUsAmazonNovaPremierV10) as Box<dyn Model>,
                Box::new(Models::BedrockUsAmazonNovaProV10) as Box<dyn Model>,
                Box::new(Models::BedrockUsAmazonNovaLiteV10) as Box<dyn Model>,
                Box::new(Models::BedrockUsAmazonNovaMicroV10) as Box<dyn Model>,
                Box::new(Models::BedrockCohereEmbedEnglishV3) as Box<dyn Model>,
                Box::new(Models::BedrockCohereEmbedMultilingualV3) as Box<dyn Model>,
                Box::new(Models::BedrockUsDeepseekR1V10) as Box<dyn Model>,
            ],
            Providers::Cloudflare => vec![
                Box::new(Models::CloudflareCfMetaLlama4Scout17b16eInstruct) as Box<dyn Model>,
                Box::new(Models::CloudflareCfMetaLlama3370bInstructFp8Fast) as Box<dyn Model>,
                Box::new(Models::CloudflareCfQwenQwq32b) as Box<dyn Model>,
                Box::new(Models::CloudflareCfQwenQwen25Coder32bInstruct) as Box<dyn Model>,
                Box::new(Models::CloudflareCfGoogleGemma312bIt) as Box<dyn Model>,
                Box::new(Models::CloudflareCfMistralaiMistralSmall3124bInstruct) as Box<dyn Model>,
                Box::new(Models::CloudflareCfBaaiBgeLargeEnV15) as Box<dyn Model>,
            ],
            Providers::Ernie => vec![
                Box::new(Models::ErnieErnie45Turbo128k) as Box<dyn Model>,
                Box::new(Models::ErnieErnie45TurboVl32k) as Box<dyn Model>,
                Box::new(Models::ErnieErnieX1Turbo32k) as Box<dyn Model>,
                Box::new(Models::ErnieBgeLargeZh) as Box<dyn Model>,
                Box::new(Models::ErnieBgeLargeEn) as Box<dyn Model>,
                Box::new(Models::ErnieBceRerankerBase) as Box<dyn Model>,
            ],
            Providers::Qianwen => vec![
                Box::new(Models::QianwenQwenMaxLatest) as Box<dyn Model>,
                Box::new(Models::QianwenQwenPlusLatest) as Box<dyn Model>,
                Box::new(Models::QianwenQwenTurboLatest) as Box<dyn Model>,
                Box::new(Models::QianwenQwenLong) as Box<dyn Model>,
                Box::new(Models::QianwenQwenOmniTurboLatest) as Box<dyn Model>,
                Box::new(Models::QianwenQwqPlusLatest) as Box<dyn Model>,
                Box::new(Models::QianwenQwenVlMaxLatest) as Box<dyn Model>,
                Box::new(Models::QianwenQwenVlPlusLatest) as Box<dyn Model>,
                Box::new(Models::QianwenQwen3235bA22b) as Box<dyn Model>,
                Box::new(Models::QianwenQwen330bA3b) as Box<dyn Model>,
                Box::new(Models::QianwenQwen332b) as Box<dyn Model>,
                Box::new(Models::QianwenQwq32b) as Box<dyn Model>,
                Box::new(Models::QianwenQwen2572bInstruct) as Box<dyn Model>,
                Box::new(Models::QianwenQwen25Vl72bInstruct) as Box<dyn Model>,
                Box::new(Models::QianwenQwen25Coder32bInstruct) as Box<dyn Model>,
                Box::new(Models::QianwenDeepseekV3) as Box<dyn Model>,
                Box::new(Models::QianwenDeepseekR10528) as Box<dyn Model>,
                Box::new(Models::QianwenTextEmbeddingV4) as Box<dyn Model>,
                Box::new(Models::QianwenTextEmbeddingV3) as Box<dyn Model>,
            ],
            Providers::Hunyuan => vec![
                Box::new(Models::HunyuanHunyuanTurbosLatest) as Box<dyn Model>,
                Box::new(Models::HunyuanHunyuanT1Latest) as Box<dyn Model>,
                Box::new(Models::HunyuanHunyuanLite) as Box<dyn Model>,
                Box::new(Models::HunyuanHunyuanTurbosVision) as Box<dyn Model>,
                Box::new(Models::HunyuanHunyuanT1Vision) as Box<dyn Model>,
                Box::new(Models::HunyuanHunyuanEmbedding) as Box<dyn Model>,
            ],
            Providers::Moonshot => vec![
                Box::new(Models::MoonshotKimiLatest) as Box<dyn Model>,
                Box::new(Models::MoonshotKimiThinkingPreview) as Box<dyn Model>,
            ],
            Providers::Deepseek => vec![
                Box::new(Models::DeepseekDeepseekChat) as Box<dyn Model>,
                Box::new(Models::DeepseekDeepseekReasoner) as Box<dyn Model>,
            ],
            Providers::Zhipuai => vec![
                Box::new(Models::ZhipuaiGlm4Plus) as Box<dyn Model>,
                Box::new(Models::ZhipuaiGlm4Air) as Box<dyn Model>,
                Box::new(Models::ZhipuaiGlm4Long) as Box<dyn Model>,
                Box::new(Models::ZhipuaiGlm4Flash250414) as Box<dyn Model>,
                Box::new(Models::ZhipuaiGlm4vPlus0111) as Box<dyn Model>,
                Box::new(Models::ZhipuaiGlm4vFlash) as Box<dyn Model>,
                Box::new(Models::ZhipuaiGlmZ1Air) as Box<dyn Model>,
                Box::new(Models::ZhipuaiGlmZ1Flash) as Box<dyn Model>,
                Box::new(Models::ZhipuaiEmbedding3) as Box<dyn Model>,
                Box::new(Models::ZhipuaiRerank) as Box<dyn Model>,
            ],
            Providers::Minimax => vec![
                Box::new(Models::MinimaxMinimaxText01) as Box<dyn Model>,
                Box::new(Models::MinimaxMinimaxM1) as Box<dyn Model>,
            ],
            Providers::Openrouter => vec![
                Box::new(Models::OpenrouterOpenaiGpt41) as Box<dyn Model>,
                Box::new(Models::OpenrouterOpenaiGpt41Mini) as Box<dyn Model>,
                Box::new(Models::OpenrouterOpenaiGpt41Nano) as Box<dyn Model>,
                Box::new(Models::OpenrouterOpenaiGpt4o) as Box<dyn Model>,
                Box::new(Models::OpenrouterOpenaiGpt4oSearchPreview) as Box<dyn Model>,
                Box::new(Models::OpenrouterOpenaiGpt4oMini) as Box<dyn Model>,
                Box::new(Models::OpenrouterOpenaiGpt4oMiniSearchPreview) as Box<dyn Model>,
                Box::new(Models::OpenrouterOpenaiChatgpt4oLatest) as Box<dyn Model>,
                Box::new(Models::OpenrouterOpenaiO4Mini) as Box<dyn Model>,
                Box::new(Models::OpenrouterOpenaiO4MiniHigh) as Box<dyn Model>,
                Box::new(Models::OpenrouterOpenaiO3Pro) as Box<dyn Model>,
                Box::new(Models::OpenrouterOpenaiO3) as Box<dyn Model>,
                Box::new(Models::OpenrouterOpenaiO3Mini) as Box<dyn Model>,
                Box::new(Models::OpenrouterOpenaiO3MiniHigh) as Box<dyn Model>,
                Box::new(Models::OpenrouterGoogleGemini25Flash) as Box<dyn Model>,
                Box::new(Models::OpenrouterGoogleGemini25Pro) as Box<dyn Model>,
                Box::new(Models::OpenrouterGoogleGemini25FlashLitePreview0617) as Box<dyn Model>,
                Box::new(Models::OpenrouterGoogleGemini20Flash001) as Box<dyn Model>,
                Box::new(Models::OpenrouterGoogleGemini20FlashLite001) as Box<dyn Model>,
                Box::new(Models::OpenrouterGoogleGemma327bIt) as Box<dyn Model>,
                Box::new(Models::OpenrouterAnthropicClaudeOpus4) as Box<dyn Model>,
                Box::new(Models::OpenrouterAnthropicClaudeSonnet4) as Box<dyn Model>,
                Box::new(Models::OpenrouterAnthropicClaude37Sonnet) as Box<dyn Model>,
                Box::new(Models::OpenrouterAnthropicClaude37SonnetThinking) as Box<dyn Model>,
                Box::new(Models::OpenrouterAnthropicClaude35Sonnet) as Box<dyn Model>,
                Box::new(Models::OpenrouterAnthropicClaude35Haiku) as Box<dyn Model>,
                Box::new(Models::OpenrouterMetaLlamaLlama4Maverick) as Box<dyn Model>,
                Box::new(Models::OpenrouterMetaLlamaLlama4Scout) as Box<dyn Model>,
                Box::new(Models::OpenrouterMetaLlamaLlama3370bInstruct) as Box<dyn Model>,
                Box::new(Models::OpenrouterMistralaiMistralMedium3) as Box<dyn Model>,
                Box::new(Models::OpenrouterMistralaiMistralSmall3224bInstruct) as Box<dyn Model>,
                Box::new(Models::OpenrouterMistralaiMagistralMedium2506) as Box<dyn Model>,
                Box::new(Models::OpenrouterMistralaiMagistralMedium2506Thinking) as Box<dyn Model>,
                Box::new(Models::OpenrouterMistralaiMagistralSmall2506) as Box<dyn Model>,
                Box::new(Models::OpenrouterMistralaiDevstralSmall) as Box<dyn Model>,
                Box::new(Models::OpenrouterMistralaiCodestral2501) as Box<dyn Model>,
                Box::new(Models::OpenrouterAi21Jamba16Large) as Box<dyn Model>,
                Box::new(Models::OpenrouterAi21Jamba16Mini) as Box<dyn Model>,
                Box::new(Models::OpenrouterCohereCommandA) as Box<dyn Model>,
                Box::new(Models::OpenrouterCohereCommandR7b122024) as Box<dyn Model>,
                Box::new(Models::OpenrouterDeepseekDeepseekChatV30324) as Box<dyn Model>,
                Box::new(Models::OpenrouterDeepseekDeepseekR10528) as Box<dyn Model>,
                Box::new(Models::OpenrouterQwenQwenMax) as Box<dyn Model>,
                Box::new(Models::OpenrouterQwenQwenPlus) as Box<dyn Model>,
                Box::new(Models::OpenrouterQwenQwenTurbo) as Box<dyn Model>,
                Box::new(Models::OpenrouterQwenQwenVlPlus) as Box<dyn Model>,
                Box::new(Models::OpenrouterQwenQwen3235bA22b) as Box<dyn Model>,
                Box::new(Models::OpenrouterQwenQwen330bA3b) as Box<dyn Model>,
                Box::new(Models::OpenrouterQwenQwen332b) as Box<dyn Model>,
                Box::new(Models::OpenrouterQwenQwq32b) as Box<dyn Model>,
                Box::new(Models::OpenrouterQwenQwen2572bInstruct) as Box<dyn Model>,
                Box::new(Models::OpenrouterQwenQwen25Vl72bInstruct) as Box<dyn Model>,
                Box::new(Models::OpenrouterQwenQwen25Coder32bInstruct) as Box<dyn Model>,
                Box::new(Models::OpenrouterXAiGrok3) as Box<dyn Model>,
                Box::new(Models::OpenrouterXAiGrok3Mini) as Box<dyn Model>,
                Box::new(Models::OpenrouterAmazonNovaProV1) as Box<dyn Model>,
                Box::new(Models::OpenrouterAmazonNovaLiteV1) as Box<dyn Model>,
                Box::new(Models::OpenrouterAmazonNovaMicroV1) as Box<dyn Model>,
                Box::new(Models::OpenrouterPerplexitySonarPro) as Box<dyn Model>,
                Box::new(Models::OpenrouterPerplexitySonar) as Box<dyn Model>,
                Box::new(Models::OpenrouterPerplexitySonarReasoningPro) as Box<dyn Model>,
                Box::new(Models::OpenrouterPerplexitySonarReasoning) as Box<dyn Model>,
                Box::new(Models::OpenrouterPerplexitySonarDeepResearch) as Box<dyn Model>,
                Box::new(Models::OpenrouterPerplexityR11776) as Box<dyn Model>,
                Box::new(Models::OpenrouterMinimaxMinimax01) as Box<dyn Model>,
                Box::new(Models::OpenrouterThudmGlm432b) as Box<dyn Model>,
                Box::new(Models::OpenrouterThudmGlmZ132b) as Box<dyn Model>,
                Box::new(Models::OpenrouterMicrosoftPhi4ReasoningPlus) as Box<dyn Model>,
            ],
            Providers::Github => vec![
                Box::new(Models::GithubGpt41) as Box<dyn Model>,
                Box::new(Models::GithubGpt41Mini) as Box<dyn Model>,
                Box::new(Models::GithubGpt41Nano) as Box<dyn Model>,
                Box::new(Models::GithubGpt4o) as Box<dyn Model>,
                Box::new(Models::GithubGpt4oMini) as Box<dyn Model>,
                Box::new(Models::GithubO4Mini) as Box<dyn Model>,
                Box::new(Models::GithubO4MiniHigh) as Box<dyn Model>,
                Box::new(Models::GithubO3) as Box<dyn Model>,
                Box::new(Models::GithubO3Mini) as Box<dyn Model>,
                Box::new(Models::GithubO3MiniHigh) as Box<dyn Model>,
                Box::new(Models::GithubTextEmbedding3Large) as Box<dyn Model>,
                Box::new(Models::GithubTextEmbedding3Small) as Box<dyn Model>,
                Box::new(Models::GithubLlama4Maverick17b128eInstructFp8) as Box<dyn Model>,
                Box::new(Models::GithubLlama4Scout17b16eInstruct) as Box<dyn Model>,
                Box::new(Models::GithubLlama3370bInstruct) as Box<dyn Model>,
                Box::new(Models::GithubMistralMedium2505) as Box<dyn Model>,
                Box::new(Models::GithubMistralSmall2503) as Box<dyn Model>,
                Box::new(Models::GithubCodestral2501) as Box<dyn Model>,
                Box::new(Models::GithubCohereEmbedV3English) as Box<dyn Model>,
                Box::new(Models::GithubCohereEmbedV3Multilingual) as Box<dyn Model>,
                Box::new(Models::GithubDeepseekR10528) as Box<dyn Model>,
                Box::new(Models::GithubDeepseekV30324) as Box<dyn Model>,
                Box::new(Models::GithubMaiDsR1) as Box<dyn Model>,
                Box::new(Models::GithubPhi4) as Box<dyn Model>,
                Box::new(Models::GithubPhi4MiniInstruct) as Box<dyn Model>,
                Box::new(Models::GithubPhi4Reasoning) as Box<dyn Model>,
                Box::new(Models::GithubPhi4MiniReasoning) as Box<dyn Model>,
                Box::new(Models::GithubGrok3) as Box<dyn Model>,
                Box::new(Models::GithubGrok3Mini) as Box<dyn Model>,
            ],
            Providers::Deepinfra => vec![
                Box::new(Models::DeepinfraMetaLlamaLlama4Maverick17b128eInstructFp8)
                    as Box<dyn Model>,
                Box::new(Models::DeepinfraMetaLlamaLlama4Scout17b16eInstruct) as Box<dyn Model>,
                Box::new(Models::DeepinfraMetaLlamaLlama3370bInstruct) as Box<dyn Model>,
                Box::new(Models::DeepinfraQwenQwen3235bA22b) as Box<dyn Model>,
                Box::new(Models::DeepinfraQwenQwen330bA3b) as Box<dyn Model>,
                Box::new(Models::DeepinfraQwenQwen332b) as Box<dyn Model>,
                Box::new(Models::DeepinfraQwenQwq32b) as Box<dyn Model>,
                Box::new(Models::DeepinfraQwenQwen2572bInstruct) as Box<dyn Model>,
                Box::new(Models::DeepinfraQwenQwen25Coder32bInstruct) as Box<dyn Model>,
                Box::new(Models::DeepinfraDeepseekAiDeepseekV30324) as Box<dyn Model>,
                Box::new(Models::DeepinfraDeepseekAiDeepseekR10528) as Box<dyn Model>,
                Box::new(Models::DeepinfraGoogleGemma327bIt) as Box<dyn Model>,
                Box::new(Models::DeepinfraMistralaiMistralSmall3224bInstruct2506) as Box<dyn Model>,
                Box::new(Models::DeepinfraMistralaiDevstralSmall2505) as Box<dyn Model>,
                Box::new(Models::DeepinfraMicrosoftPhi4ReasoningPlus) as Box<dyn Model>,
                Box::new(Models::DeepinfraBaaiBgeLargeEnV15) as Box<dyn Model>,
                Box::new(Models::DeepinfraBaaiBgeM3) as Box<dyn Model>,
                Box::new(Models::DeepinfraIntfloatE5LargeV2) as Box<dyn Model>,
                Box::new(Models::DeepinfraIntfloatMultilingualE5Large) as Box<dyn Model>,
                Box::new(Models::DeepinfraThenlperGteLarge) as Box<dyn Model>,
            ],
            Providers::Jina => vec![
                Box::new(Models::JinaJinaEmbeddingsV3) as Box<dyn Model>,
                Box::new(Models::JinaJinaClipV2) as Box<dyn Model>,
                Box::new(Models::JinaJinaColbertV2) as Box<dyn Model>,
                Box::new(Models::JinaJinaRerankerV2BaseMultilingual) as Box<dyn Model>,
                Box::new(Models::JinaJinaColbertV2) as Box<dyn Model>,
            ],
            Providers::Voyageai => vec![
                Box::new(Models::VoyageaiVoyage3Large) as Box<dyn Model>,
                Box::new(Models::VoyageaiVoyage3) as Box<dyn Model>,
                Box::new(Models::VoyageaiVoyage3Lite) as Box<dyn Model>,
                Box::new(Models::VoyageaiRerank2) as Box<dyn Model>,
                Box::new(Models::VoyageaiRerank2Lite) as Box<dyn Model>,
            ],
        }
    }
    fn name(&self) -> &str {
        match self {
            Providers::Openai => "openai",
            Providers::Gemini => "gemini",
            Providers::Claude => "claude",
            Providers::Mistral => "mistral",
            Providers::Ai21 => "ai21",
            Providers::Cohere => "cohere",
            Providers::Xai => "xai",
            Providers::Perplexity => "perplexity",
            Providers::Groq => "groq",
            Providers::Vertexai => "vertexai",
            Providers::Bedrock => "bedrock",
            Providers::Cloudflare => "cloudflare",
            Providers::Ernie => "ernie",
            Providers::Qianwen => "qianwen",
            Providers::Hunyuan => "hunyuan",
            Providers::Moonshot => "moonshot",
            Providers::Deepseek => "deepseek",
            Providers::Zhipuai => "zhipuai",
            Providers::Minimax => "minimax",
            Providers::Openrouter => "openrouter",
            Providers::Github => "github",
            Providers::Deepinfra => "deepinfra",
            Providers::Jina => "jina",
            Providers::Voyageai => "voyageai",
        }
    }
}

impl Providers {
    /// Create a Providers enum from a string name
    pub fn from_name(name: &str) -> Option<Self> {
        match name.to_lowercase().as_str() {
            "openai" => Some(Providers::Openai),
            "gemini" => Some(Providers::Gemini),
            "claude" => Some(Providers::Claude),
            "mistral" => Some(Providers::Mistral),
            "ai21" => Some(Providers::Ai21),
            "cohere" => Some(Providers::Cohere),
            "xai" => Some(Providers::Xai),
            "perplexity" => Some(Providers::Perplexity),
            "groq" => Some(Providers::Groq),
            "vertexai" => Some(Providers::Vertexai),
            "bedrock" => Some(Providers::Bedrock),
            "cloudflare" => Some(Providers::Cloudflare),
            "ernie" => Some(Providers::Ernie),
            "qianwen" => Some(Providers::Qianwen),
            "hunyuan" => Some(Providers::Hunyuan),
            "moonshot" => Some(Providers::Moonshot),
            "deepseek" => Some(Providers::Deepseek),
            "zhipuai" => Some(Providers::Zhipuai),
            "minimax" => Some(Providers::Minimax),
            "openrouter" => Some(Providers::Openrouter),
            "github" => Some(Providers::Github),
            "deepinfra" => Some(Providers::Deepinfra),
            "jina" => Some(Providers::Jina),
            "voyageai" => Some(Providers::Voyageai),
            _ => None,
        }
    }
}
