[profile.default]
# Test runner configuration for fluent-ai-candle package
retries = 0
failure-output = "immediate"
success-output = "never"

[profile.default.junit]
path = "target/nextest/default/junit.xml"

[profile.ci]
# CI-specific settings with stricter timeouts
retries = 2
failure-output = "immediate"
success-output = "never"

[profile.ci.junit]
path = "target/nextest/ci/junit.xml"

[profile.quick]
# Quick testing profile for development
retries = 0
failure-output = "immediate"
success-output = "never"