//! Workspace hack for fluent-ai
//! 
//! This crate is automatically generated by cargo-hakari to optimize build times
//! by unifying dependency features across the workspace.

// This file is automatically @generated by cargo-hakari.
// It is not intended for manual editing.