//! Fluent AI Provider Library
//!
//! This crate provides provider and model implementations for AI services.
//! The core domain types are now defined in the domain package.

// Include generated code from build script
include!(concat!(env!("OUT_DIR"), "/providers.rs"));
include!(concat!(env!("OUT_DIR"), "/models.rs"));

// Re-export domain types for backward compatibility
pub use fluent_ai_domain::model::ModelInfo;

// Provider client implementations
pub mod clients;

// Image processing implementations
pub mod image_processing;

// Model discovery and registration
pub mod discovery;

// Re-export Candle client for convenience
#[cfg(feature = "candle")]
pub use clients::candle::{CandleCompletionClient, CandleModel, CandleProvider};

// Client factory for provider-to-client mapping
pub mod client_factory;

// Security and credential management
pub mod security;

// Client traits (NOT domain objects)
pub mod client;

// Universal completion provider trait
pub mod completion_provider;

// Re-export client traits for provider implementations
pub use client::*;
pub use completion_provider::*;
pub use cyrup_sugars::{OneOrMany, ZeroOneOrMany};
// Re-export fluent-ai types for provider implementations
pub use fluent_ai_domain as domain;
pub use fluent_ai_domain::AsyncTask;
pub use fluent_ai_domain::spawn_async;
// pub use crate::Provider; // TODO: Define Provider trait

// Re-export json_util for provider implementations
pub use fluent_ai_domain::json_util;

// Create our own AsyncStream type for provider compatibility
pub type AsyncStream<T> = tokio_stream::wrappers::UnboundedReceiverStream<T>;
pub type AsyncStreamSender<T> = tokio::sync::mpsc::UnboundedSender<T>;

// Helper to create async stream channel
pub fn async_stream_channel<T>() -> (AsyncStreamSender<T>, AsyncStream<T>) {
    let (tx, rx) = tokio::sync::mpsc::unbounded_channel();
    (tx, tokio_stream::wrappers::UnboundedReceiverStream::new(rx))
}

// Extension methods for Providers enum will be auto-generated by build.rs
