//! Fluent AI Provider Library
//!
//! This crate provides provider and model implementations for AI services.
//! The core domain types are now defined in the domain package.

// Include generated code from build script
include!(concat!(env!("OUT_DIR"), "/providers.rs"));
include!(concat!(env!("OUT_DIR"), "/models.rs"));

// Re-export domain types for backward compatibility
pub use fluent_ai_domain::model::ModelInfo;

// Provider client implementations
pub mod clients;

// Image processing implementations
pub mod image_processing;

// Model discovery and registration
pub mod discovery;

// Re-export Candle client for convenience
#[cfg(feature = "candle")]
pub use clients::candle::{CandleCompletionClient, CandleModel, CandleProvider};

// Client factory for provider-to-client mapping
pub mod client_factory;

// Security and credential management
pub mod security;

// Client traits (NOT domain objects)
pub mod client;

// Universal completion provider trait
pub mod completion_provider;

// Streaming interface implementations
pub mod streaming;

// Embedding interface implementations
pub mod embeddings;

// Transcription interface implementations
pub mod transcription;

// HTTP3 streaming trait architecture
pub mod http3_streaming;

// Re-export client traits for provider implementations
pub use client::*;
pub use completion_provider::*;
pub use cyrup_sugars::{OneOrMany, ZeroOneOrMany};
pub use embeddings::*;
pub use fluent_ai_async::AsyncStream;
// Use canonical streaming types from fluent-ai-async
pub use fluent_ai_async::{AsyncStreamSender, channel};
// Re-export fluent-ai types for provider implementations
pub use fluent_ai_domain as domain;
pub use fluent_ai_domain::AsyncTask;
// pub use crate::Provider; // TODO: Define Provider trait

// Re-export json_util for provider implementations
pub use fluent_ai_domain::json_util;
pub use fluent_ai_domain::spawn_async;
pub use http3_streaming::*;
pub use streaming::*;
pub use transcription::*;

// Extension methods for Providers enum will be auto-generated by build.rs
