[package]
name = "fluent_ai_candle"
version = "0.1.0"
edition = "2021"
description = "High-performance candle integration for fluent-ai completion system"
license = "MIT OR Apache-2.0"

[dependencies]
# Candle ML framework dependencies (CPU-only)
candle-core = { version = "0.9.1", default-features = false, features = [] }
candle-nn = { version = "0.9.1", default-features = false, features = [] }
candle-transformers = { version = "0.9.1", default-features = false, features = [] }

# Tokenization and model loading
tokenizers = "0.21.0"
hf-hub = "0.4.1"
safetensors = "0.4.1"

# Zero-allocation data structures
arrayvec = "0.7.4"
smallvec = "1.11.2"

# Lock-free concurrency
crossbeam = "0.8.3"
crossbeam-channel = "0.5.8"
crossbeam-skiplist = "0.1.3"
arc-swap = "1.6.0"

# Performance optimizations
memmap2 = "0.9.0"
wide = "0.7.13"
parking_lot = "0.12.1"

# Async runtime
tokio = { version = "1.35", features = ["full"] }

# Serialization
serde = { version = "1.0.193", features = ["derive"] }
serde_json = "1.0.108"

# Error handling
thiserror = "1.0.50"
anyhow = "1.0.75"

# Logging
tracing = "0.1.40"

# Security
zeroize = "1.6.0"

# Local dependencies
fluent_ai_domain = { path = "../domain" }

[features]
default = ["metal"]
cuda = ["candle-core/cuda", "candle-nn/cuda", "candle-transformers/cuda"]
metal = ["candle-core/metal", "candle-nn/metal", "candle-transformers/metal"]
mkl = ["candle-core/mkl"]
accelerate = ["candle-core/accelerate"]

[dev-dependencies]
criterion = "0.5.1"
tempfile = "3.8.1"