[package]
name = "fluent_ai_candle"
version = "0.1.0"
edition = "2021"
description = "High-performance candle integration for fluent-ai completion system"
license = "MIT OR Apache-2.0"

[dependencies]
fluent-ai-workspace-hack = { version = "0.1", path = "../../workspace-hack" }
fluent_ai_core = { package = "fluent-ai-core", version = "0.1.0", path = "../fluent-ai-core" }

# Candle dependencies (optional, enabled by features)
candle-core = { git = "https://github.com/huggingface/candle", branch = "main", default-features = false }
candle-nn = { git = "https://github.com/huggingface/candle", branch = "main", default-features = false }
candle-transformers = { git = "https://github.com/huggingface/candle", branch = "main", default-features = false }
candle-flash-attn = { git = "https://github.com/huggingface/candle", branch = "main", default-features = false, optional = true }
candle-onnx = { git = "https://github.com/huggingface/candle", branch = "main", default-features = false, optional = true }
candle-datasets = { git = "https://github.com/huggingface/candle", branch = "main", default-features = false, optional = true }

# — Optional acceleration dependencies —
half = { version = "2.6.0", optional = true }
rubato     = { version = "1.0.0-preview.0", optional = true }                                                 # FFT resampler
symphonia = { version = "0.5.4", optional = true }
image = { version = "0.25.6", optional = true }
palette = { version = "0.7.6", optional = true }
enterpolation = { version = "0.3.0", optional = true }
tokenizers = "0.21.2"  # Required for tokenizer functionality
safetensors = "0.6.0"  # Required for model loading
dioxus = { git = "https://github.com/DioxusLabs/dioxus", branch = "main", optional = true }
js-sys = { version = "0.3.77", optional = true }
wasm-bindgen = { version = "0.2.100", optional = true }
gloo-timers = { version = "0.3", optional = true, features = ["futures"] }
cpal = { version = "0.16.0", optional = true }


# Zero-allocation data structures
arrayvec = "0.7.6"
arraystring = "0.3.0"
smallvec = "2.0.0-alpha.11"

# Lock-free concurrency
crossbeam = "0.8.4"
crossbeam-channel = "0.5.15"
crossbeam-skiplist = "0.1.3"
crossbeam-utils = "0.8.21"
arc-swap = "1.7.1"

# Performance optimizations
memmap2 = "0.9.7"
wide = "0.7.33"
parking_lot = "0.12.4"

# SIMD operations using wide crate instead

# Async runtime
tokio = { version = "1.46.1", features = ["full"] }
tokio-stream = "0.1.16"
futures = "0.3.31"
futures-util = "0.3.31"
async-stream = "0.3.6"

# Random number generation
fastrand = "2.3.0"
rand = "0.9.2"

# Serialization
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.141"

# Error handling
thiserror = "2.0.12"
anyhow = "1.0.98"

# System directories
dirs = "6.0.0"

# Logging
tracing = "0.1.41"

# Security
zeroize = "1.8.1"

# Local dependencies
# fluent_ai_domain = { path = "../domain" } # Temporarily disabled to test candle compilation
# fluent_ai_provider = { path = "../provider" } # Temporarily disabled due to domain dependency

# External ML dependencies  
fluent_ai_http3 = { path = "../http3" }
fluent-ai-simd = { path = "../fluent-ai-simd" }
sha2 = "0.10.8"
httpdate = "1.0.3"


[features]
default = ["microphone", "metal"]  # macOS-optimized defaults with Metal acceleration
# --- Candle backend features (required for all candle crates) -----
cuda = ["candle-core/cuda", "candle-nn/cuda", "dep:cudarc", "dep:half", "dep:bindgen_cuda", "candle-transformers/cuda"]
cudnn = ["candle-core/cudnn", "candle-nn/cudnn", "candle-transformers/cudnn"]
metal = ["candle-core/metal", "candle-nn/metal", "candle-transformers/metal"]
accelerate = ["dep:accelerate-src", "candle-core/accelerate", "candle-nn/accelerate", "candle-transformers/accelerate"]
mkl = ["dep:intel-mkl-src", "candle-core/mkl", "candle-nn/mkl", "candle-transformers/mkl"]
flash-attn = ["cuda", "dep:candle-flash-attn", "candle-transformers/flash-attn"]
nccl = ["cuda", "cudarc/nccl", "dep:half"]
onnx = ["dep:candle-onnx"]
# UI features
ui = ["dioxus", "js-sys", "wasm-bindgen", "gloo-timers"]

# Audio processing features
microphone = ["dep:cpal", "dep:rubato"]
encodec = ["dep:cpal", "dep:symphonia", "dep:rubato"]
mimi = ["dep:cpal", "dep:symphonia", "dep:rubato"]
snac = ["dep:cpal", "dep:symphonia", "dep:rubato"]
depth_anything_v2 = ["dep:palette", "dep:enterpolation"]

# OS-specific acceleration dependencies
[target.'cfg(all(target_os = "linux", target_arch = "x86_64"))'.dependencies]
cudarc = { version = "0.16.6", optional = true, default-features = false, features = ["cublas", "cublaslt", "cudnn", "curand", "dynamic-linking", "f16", "std"] }
intel-mkl-src = { version = "0.8.1", optional = true }
bindgen_cuda = { version = "0.1.5", optional = true }

[target.'cfg(all(target_os = "windows", target_arch = "x86_64"))'.dependencies]
cudarc = { version = "0.16.6", optional = true, default-features = false, features = ["cublas", "cublaslt", "cudnn", "curand", "dynamic-linking", "f16", "std"] }
intel-mkl-src = { version = "0.8.1", optional = true }
bindgen_cuda = { version = "0.1.5", optional = true }

[target.'cfg(target_os = "macos")'.dependencies]
accelerate-src = { version = "0.3.2", optional = true }



[dev-dependencies]
criterion = "0.6.0"
tempfile = "3.20.0"
