// Generated code - DO NOT EDIT MANUALLY
// This file is automatically generated by build.rs
// Successfully processed 1/6 providers
// Failed providers: No models found for openai, No models found for mistral, No models found for xai, No models found for together, No API key configured and no static models for huggingface

// Provider implementations will be added here by each provider's process() method
