[package]
name = "fluent_ai_provider"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
cyrup_sugars = { git = "https://github.com/cyrup-ai/cyrup-sugars", rev = "cc262c4aa90493a6cf6ae4695b7dad28b0c1199d" }
fluent_ai_domain = { path = "../domain" }
serde_yaml = "0.9"
reqwest = { version = "0.12", features = ["json", "stream", "http3", "rustls-tls", "rustls-tls-native-roots"] }
tokio = { version = "1.0", features = ["full"] }
serde_json = "1.0"
thiserror = "1.0"
futures = "0.3"
hashbrown = { version = "0.15", features = ["serde"] }

[build-dependencies]
reqwest = { version = "0.12", features = ["json", "http3", "rustls-tls", "rustls-tls-native-roots"] }
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1.0", features = ["full"] }
serde_json = "1.0.140"
syn = { version = "2.0.104", features = ["full", "parsing"] }
quote = "1.0.40"
proc-macro2 = "1.0.95"
serde_yaml = "0.9"

[lib]
name = "fluent_ai_provider"
path = "src/lib.rs"
