[package]
name = "fluent_ai_provider"
version = "0.1.0"
edition = "2024"

[dependencies]
yyaml = { git = "https://github.com/cyrup-ai/yyaml", branch = "main"}
serde = { version = "1.0", features = ["derive"] }
cyrup_sugars = { git = "https://github.com/cyrup-ai/cyrup-sugars", features = ["all"] }
fluent_ai_domain = { path = "../domain" }
fluent_ai_http3 = { path = "../http3" }
tokio = { version = "1.46.1", features = ["full"] }
tokio-stream = "0.1"
serde_json = "1.0"
thiserror = "2.0.12"
futures = "0.3"
hashbrown = { version = "0.15", features = ["serde"] }
http = "1.3.1"
once_cell = "1.21.3"
fastrand = "2.3.0"
regex = "1.10"
base64 = "0.22"
bytes = "1.10.1"
futures-util = "0.3"
async-stream = "0.3"
mime_guess = "2.0"
tracing = "0.1"
arrayvec = "0.7"
termcolor = { path = "../termcolor" }

[build-dependencies]
fluent_ai_http3 = { path = "../http3" }
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1.46.1", features = ["full"] }
serde_json = "1.0.140"
syn = { version = "2.0.104", features = ["full", "parsing"] }
quote = "1.0.40"
proc-macro2 = "1.0.95"
serde_yaml = "0.9"
yyaml = { git = "https://github.com/cyrup-ai/yyaml", branch = "main"}
once_cell = "1.21.3"

[lib]
name = "fluent_ai_provider"
path = "src/lib.rs"
