[package]
name = "fluent_ai_provider"
version = "0.1.0"
edition = "2024"
# Build script for code generation
build = "build.rs"

[features]
# Default features - metal for macOS optimization
default = ["metal"]

# Core build flavours
desktop = []

# Candle backend features (required for all candle crates)
cuda = ["candle-core/cuda", "candle-nn/cuda", "dep:cudarc", "dep:half", "dep:bindgen_cuda", "candle-transformers?/cuda"]
cudnn = ["candle-core/cudnn", "candle-nn/cudnn", "candle-transformers?/cudnn"]
metal = ["candle-core/metal", "candle-nn/metal", "candle-transformers?/metal"]
accelerate = ["dep:accelerate-src", "candle-core/accelerate", "candle-nn/accelerate", "candle-transformers?/accelerate"]
mkl = ["dep:intel-mkl-src", "candle-core/mkl", "candle-nn/mkl", "candle-transformers?/mkl"]
flash-attn = ["cuda", "dep:candle-flash-attn", "candle-transformers?/flash-attn"]
nccl = ["cuda", "cudarc/nccl", "dep:half"]
onnx = ["dep:candle-onnx"]

# Optional extended functionality
image = ["dep:image", "dep:candle-transformers"]
generation = ["dep:candle-transformers", "dep:hf-hub", "dep:tokenizers", "dep:safetensors"]

[dependencies]
fluent-ai-workspace-hack = { path = "../../workspace-hack" }
yyaml = { git = "https://github.com/cyrup-ai/yyaml", branch = "main"}
serde = { version = "1.0", features = ["derive"] }
cyrup_sugars = { git = "https://github.com/cyrup-ai/cyrup-sugars", features = ["all"] }
fluent_ai_domain = { version = "0.1.0", path = "../domain" }
fluent_ai_http3 = { path = "../http3" }
tokio = { version = "1.46.1", features = ["full"] }
tokio-stream = "0.1"
serde_json = "1.0"
thiserror = "2.0.12"
futures = "0.3"
hashbrown = { version = "0.15", features = ["serde"] }
http = "1.3.1"
once_cell = "1.21.3"
fastrand = "2.3.0"
regex = "1.10"
base64 = "0.22"
bytes = "1.10.1"
pest = "2.8.1"
pest_derive = "2.8.1"
futures-util = "0.3"
async-stream = "0.3"
mime_guess = "2.0"
tracing = "0.1"
arrayvec = "0.7"
termcolor = { path = "../termcolor" }

# Build system dependencies for zero-allocation processing
crossbeam = "0.8"             # Lock-free data structures and channels
rustc-hash = "2.0"            # Fast hash maps optimized for string keys  
memmap2 = "0.9"               # Memory-mapped file I/O for caching
wide = "0.7"                  # SIMD acceleration for string processing
arc-swap = "1.7"              # Atomic lock-free reference swapping
smallvec = "2.0.0-alpha.11"   # Stack-allocated vectors for small collections

# Security and credential management dependencies
chacha20poly1305 = "0.10"     # Authenticated encryption for credential storage
uuid = { version = "1.5", features = ["v4"] }  # UUID generation for audit logs
bincode = "1.3"               # Binary serialization for encrypted data
zeroize = { version = "1.6", features = ["derive"] }  # Memory zeroing for security
dashmap = "6.1"               # Lock-free concurrent hash map
rand = "0.8"                  # Cryptographically secure random number generation
chrono = { version = "0.4", features = ["serde"] }  # Date/time handling for audit logs
hostname = "0.4"              # System hostname for audit metadata
tempfile = "3.8"              # Temporary files for testing

# Cryptographic dependencies for AWS SigV4 signing
sha2 = "0.10"       # SHA-256 hashing for AWS signature generation
hmac = "0.12"       # HMAC for AWS signature generation

# Candle ML framework dependencies (from GitHub main)
candle-core = { git = "https://github.com/huggingface/candle", branch = "main", default-features = false }
candle-nn = { git = "https://github.com/huggingface/candle", branch = "main", default-features = false }
candle-transformers = { git = "https://github.com/huggingface/candle", branch = "main", default-features = false, optional = true }
candle-flash-attn = { git = "https://github.com/huggingface/candle", branch = "main", default-features = false, optional = true }
candle-onnx = { git = "https://github.com/huggingface/candle", branch = "main", default-features = false, optional = true }
candle-datasets = { git = "https://github.com/huggingface/candle", branch = "main", default-features = false, optional = true }

# ML/AI dependencies  
image = { version = "0.25.6", optional = true }
hf-hub = { version = "0.4.3", features = ["tokio"], optional = true }
tokenizers = { version = "0.21", features = ["onig"], optional = true }
safetensors = { version = "0.6", optional = true }
rayon = "1.10"                # CPU parallelism for inference optimization

# Optional acceleration dependencies
half = { version = "2.6", optional = true }
parking_lot = "0.12.4"

[build-dependencies]
fluent_ai_http3 = { path = "../http3" }
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1.46.1", features = ["full"] }
serde_json = "1.0.140"
syn = { version = "2.0.104", features = ["full", "parsing"] }
quote = "1.0.40"
proc-macro2 = "1.0.95"
serde_yaml = "0.9"
yyaml = { git = "https://github.com/cyrup-ai/yyaml", branch = "main"}

# Build system dependencies for zero-allocation processing
arrayvec = "0.7"              # Stack-allocated vectors for small collections
crossbeam = "0.8"             # Lock-free data structures and channels
rustc-hash = "2.0"            # Fast hash maps optimized for string keys
memmap2 = "0.9"               # Memory-mapped file I/O for caching
wide = "0.7"                  # SIMD acceleration for string processing
arc-swap = "1.7"              # Atomic lock-free reference swapping
smallvec = "2.0.0-alpha.11"   # Stack-allocated vectors for small collections
once_cell = "1.21.3"
async-trait = "0.1.88"
log = "0.4.27"
thiserror = "2.0.12"
bincode = "1.3"
lru = "0.16.0"
twox-hash = "2.1.1"
futures = "0.3"
parking_lot = "0.12"

# OS-specific acceleration dependencies
[target.'cfg(all(target_os = "linux", target_arch = "x86_64"))'.dependencies]
cudarc = { version = "0.16", optional = true, default-features = false, features = ["cublas", "cublaslt", "cudnn", "curand", "dynamic-linking", "f16", "std"] }
intel-mkl-src = { version = "0.8", optional = true }

[target.'cfg(all(target_os = "windows", target_arch = "x86_64"))'.dependencies]
cudarc = { version = "0.16", optional = true, default-features = false, features = ["cublas", "cublaslt", "cudnn", "curand", "dynamic-linking", "f16", "std"] }
intel-mkl-src = { version = "0.8", optional = true }

[target.'cfg(target_os = "macos")'.dependencies]
accelerate-src = { version = "0.3", optional = true }

[target.'cfg(all(target_os = "linux", target_arch = "x86_64"))'.build-dependencies]
bindgen_cuda = { version = "0.1.5", optional = true }

[target.'cfg(all(target_os = "windows", target_arch = "x86_64"))'.build-dependencies]
bindgen_cuda = { version = "0.1.5", optional = true }

[lib]
name = "fluent_ai_provider"
path = "src/lib.rs"
