# Valid nextest configuration for fluent-ai workspace
[profile.default]
# Run tests in parallel using all available cores
test-threads = "num-cpus"

# Retry flaky tests up to 3 times
retries = 3

# Fail the entire test run if any test takes longer than 5 minutes
slow-timeout = { period = "300s", terminate-after = 2 }