[package]
name = "fluent_ai"
description = "Pure Traits & Builders over any AI Framework"
version = "0.1.0"
edition = "2024"

[features]
default = ["hashbrown-json"]
hashbrown-json = []
audio = []
image = ["dep:image"]
cylo = ["dep:cylo"]

[dependencies]
cylo = { path = "../cylo", optional = true }
fluent-ai-workspace-hack = { path = "../../workspace-hack" }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.141"
serde_path_to_error = "0.1.17"
# futures = "0.3.31" # REMOVED: Use AsyncStream only
# futures-util = "0.3.31" # REMOVED: Use AsyncStream only
tokio = { version = "1.47.0", features = ["full"] }
bytes = "1.10.1"
fluent_ai_domain = { path = "../domain" }
fluent_ai_provider = { path = "../provider" }
model-info = { path = "../model-info" }
fluent_ai_async = { path = "../async-stream" }
termcolor = { path = "../termcolor" }
fastrand = "2.3.0"
thiserror = "2.0.12"
parking_lot = "0.12.4"
hashbrown = { version = "0.15.4", features = [
    "inline-more"
] }
uuid = { version = "1.17.0", features = ["v4"] }
indexmap = "2.10.0"
fluent_ai_http3 = { path = "../http3" }
http = "1.3.1"
mime_guess = "2.0.5"
base64 = "0.22.1"
glob = "0.3.2"
gix-hash = "0.19.0"
arrayvec = "0.7.6"
atomic-counter = "1.0.1"

cyrup_sugars = { git = "https://github.com/cyrup-ai/cyrup-sugars", branch = "main", package = "cyrup_sugars", features = ["all"] }

# PDF/EPUB loader dependencies
lopdf = "0.36.0"
epub = "2.1.4"
quick-xml = "0.38.0"

# Zeroshot integration dependencies
pulldown-cmark = "0.13.0"
syntect = "5.2"
ratatui = { git = "https://github.com/ratatui-org/ratatui", branch = "main" }
smallvec = "2.0.0-alpha.11"
once_cell = "1.21.3"
crossterm = "0.29.0"
crossbeam = "0.8.4"
crossbeam-channel = "0.5.15"
crossbeam-queue = "0.3.12"
crossbeam-skiplist = "0.1.3"
dashmap = "6.1.0"
arc-swap = "1.7.1"
wide = "0.7"
futures-util = "0.3.31"
lazy_static = "1.5.0"

# HTTP3 library (mandatory per CLAUDE.md)
# Note: Removed forbidden HTTP libraries (reqwest, reqwest-eventsource, tokio-tungstenite)
# All HTTP operations must use fluent_ai_http3 exclusively
tracing = "0.1.41"

# Additional core dependencies
# futures-core = "0.3.31" # REMOVED: Use AsyncStream only
schemars = "1.0.4"
# async-stream = "0.3.6" # REMOVED: Use internal fluent_ai_async
crossbeam-deque = "0.8.6"
anyhow = "1.0.98"
# futures-executor = "0.3.31" # REMOVED: Use AsyncStream only

# Candle ML framework dependencies (needed for embedding providers)
candle-core = { version = "0.9.1", optional = true }
candle-nn = { version = "0.9.1", optional = true }

# ML/AI dependencies
image = { version = "0.25.6", optional = true }
hf-hub = { version = "0.4.3", features = ["tokio"], optional = true }
tokenizers = { version = "0.21.4", features = ["onig"], optional = true }
safetensors = { version = "0.6.0", optional = true }

# Optional acceleration dependencies
half = { version = "2.6.0", optional = true }
crossbeam-utils = "0.8.21"

[lib]
name = "fluent_ai"
path = "src/lib.rs"

# OS-specific acceleration dependencies
[target.'cfg(all(target_os = "linux", target_arch = "x86_64"))'.dependencies]
cudarc = { version = "0.17", optional = true, default-features = false, features = ["cublas", "cublaslt", "cudnn", "curand", "dynamic-linking", "f16", "std"] }
intel-mkl-src = { version = "0.8.1", optional = true }

[target.'cfg(all(target_os = "windows", target_arch = "x86_64"))'.dependencies]
cudarc = { version = "0.17.0", optional = true, default-features = false, features = ["cublas", "cublaslt", "cudnn", "curand", "dynamic-linking", "f16", "std"] }
intel-mkl-src = { version = "0.8.1", optional = true }

[target.'cfg(target_os = "macos")'.dependencies]
accelerate-src = { version = "0.3.2", optional = true }

[target.'cfg(all(target_os = "linux", target_arch = "x86_64"))'.build-dependencies]
bindgen_cuda = { version = "0.1.5", optional = true }

[target.'cfg(all(target_os = "windows", target_arch = "x86_64"))'.build-dependencies]
bindgen_cuda = { version = "0.1.5", optional = true }

[dev-dependencies]
tokio = { version = "1.47.0", features = ["macros", "rt-multi-thread"] }
