[package]
name = "fluent_ai"
description = "Pure Traits & Builders over any AI Framework"
version = "0.1.0"
edition = "2024"

[features]
default = ["hashbrown-json"]
hashbrown-json = []
audio = []
image = ["dep:image"]

[dependencies]
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
serde_path_to_error = "0.1"
futures = "0.3"
futures-util = "0.3"
tokio = { version = "1.46.1", features = ["full"] }
bytes = "1.10.1"
fluent_ai_domain = { path = "../domain" }
fluent_ai_provider = { path = "../provider" }
termcolor = { path = "../termcolor" }
fastrand = "2.3.0"
thiserror = "2.0.12"
parking_lot = "0.12.4"
hashbrown = { version = "0.15.4", features = [
    "inline-more"
] }
uuid = { version = "1.17.0", features = ["v4"] }
indexmap = "2.10.0"
fluent_ai_http3 = { path = "../http3" }
http = "1.3.1"
mime_guess = "2.0"
base64 = "0.22"
glob = "0.3"
gix-hash = "0.19.0"
# workspace-hack = { version = "0.1", path = "../workspace-hack" }
sweetmcp_memory = { git = "https://github.com/cyrup-ai/sweetmcp", package = "sweetmcp_memory", branch = "main" }
cyrup_sugars = { git = "https://github.com/cyrup-ai/cyrup-sugars", package = "cyrup_sugars", branch = "main", features = ["all"] }
sugars_macros = { git = "https://github.com/cyrup-ai/cyrup-sugars", package = "sugars_macros", branch = "main" }

# PDF/EPUB loader dependencies
lopdf = "0.36.0"
epub = "2.0.0"
quick-xml = "0.38.0"

# Zeroshot integration dependencies
pulldown-cmark = "0.13.0"
syntect = "5.2"
ratatui = { git = "https://github.com/ratatui-org/ratatui", branch = "main" }
smallvec = "1.13"
once_cell = "1.20"
crossterm = "0.29.0"
crossbeam-channel = "0.5"
crossbeam-queue = "0.3"
lazy_static = "1.4"

# Streaming and WebSocket dependencies
reqwest = { version = "0.12.22", features = ["json", "stream", "http3", "rustls-tls", "rustls-tls-native-roots", "rustls-tls-manual-roots", "gzip", "deflate", "brotli"] }
reqwest-eventsource = "0.6.0"
tokio-tungstenite = "0.27.0"
tracing = "0.1.41"

# Additional core dependencies
futures-core = "0.3.31"
schemars = "1.0.4"
async-stream = "0.3.6"
crossbeam-deque = "0.8.6"
anyhow = "1.0"
futures-executor = "0.3"

# Candle ML framework dependencies (from GitHub main)
candle-core = { git = "https://github.com/huggingface/candle", branch = "main", default-features = false }
candle-nn = { git = "https://github.com/huggingface/candle", branch = "main", default-features = false }
candle-transformers = { git = "https://github.com/huggingface/candle", branch = "main", default-features = false, optional = true }
candle-flash-attn = { git = "https://github.com/huggingface/candle", branch = "main", default-features = false, optional = true }
candle-onnx = { git = "https://github.com/huggingface/candle", branch = "main", default-features = false, optional = true }
candle-datasets = { git = "https://github.com/huggingface/candle", branch = "main", default-features = false, optional = true }

# ML/AI dependencies
image = { version = "0.25.6", optional = true }
hf-hub = { version = "0.4.3", features = ["tokio"], optional = true }
tokenizers = { version = "0.21", features = ["onig"], optional = true }
safetensors = { version = "0.6", optional = true }

# Optional acceleration dependencies
half = { version = "2.6", optional = true }

[lib]
name = "fluent_ai"
path = "src/lib.rs"

# OS-specific acceleration dependencies
[target.'cfg(all(target_os = "linux", target_arch = "x86_64"))'.dependencies]
cudarc = { version = "0.16", optional = true, default-features = false, features = ["cublas", "cublaslt", "cudnn", "curand", "dynamic-linking", "f16", "std"] }
intel-mkl-src = { version = "0.8", optional = true }

[target.'cfg(all(target_os = "windows", target_arch = "x86_64"))'.dependencies]
cudarc = { version = "0.16", optional = true, default-features = false, features = ["cublas", "cublaslt", "cudnn", "curand", "dynamic-linking", "f16", "std"] }
intel-mkl-src = { version = "0.8", optional = true }

[target.'cfg(target_os = "macos")'.dependencies]
accelerate-src = { version = "0.3", optional = true }

[target.'cfg(all(target_os = "linux", target_arch = "x86_64"))'.build-dependencies]
bindgen_cuda = { version = "0.1.5", optional = true }

[target.'cfg(all(target_os = "windows", target_arch = "x86_64"))'.build-dependencies]
bindgen_cuda = { version = "0.1.5", optional = true }

[dev-dependencies]
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
