[package]
name = "fluent_ai"
description = "Pure Traits & Builders over any AI Framework"
version = "0.1.0"
edition = "2024"

[features]
default = ["hashbrown-json"]
hashbrown-json = []
audio = []
image = ["dep:image"]
cylo = ["dep:cylo"]

[dependencies]
cylo = { path = "../cylo", optional = true }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.141"
serde_path_to_error = "0.1.17"
futures = "0.3.31"
futures-util = "0.3.31"
tokio = { version = "1.46.1", features = ["full"] }
bytes = "1.10.1"
fluent_ai_domain = { path = "../domain" }
fluent_ai_provider = { path = "../provider" }
termcolor = { path = "../termcolor" }
fastrand = "2.3.0"
thiserror = "2.0.12"
parking_lot = "0.12.4"
hashbrown = { version = "0.15.4", features = [
    "inline-more"
] }
uuid = { version = "1.17.0", features = ["v4"] }
indexmap = "2.10.0"
fluent_ai_http3 = { path = "../http3" }
http = "1.3.1"
mime_guess = "2.0.5"
base64 = "0.22.1"
glob = "0.3.2"
gix-hash = "0.19.0"
fluent-ai-workspace-hack = { version = "0.1", path = "../../workspace-hack" }

cyrup_sugars = { git = "https://github.com/cyrup-ai/cyrup-sugars", package = "cyrup_sugars", branch = "main", features = ["all"] }
sugars_macros = { git = "https://github.com/cyrup-ai/cyrup-sugars", package = "sugars_macros", branch = "main" }

# PDF/EPUB loader dependencies
lopdf = "0.36.0"
epub = "2.1.4"
quick-xml = "0.38.0"

# Zeroshot integration dependencies
pulldown-cmark = "0.13.0"
syntect = "5.2"
ratatui = { git = "https://github.com/ratatui-org/ratatui", branch = "main" }
smallvec = "2.0.0-alpha.11"
once_cell = "1.21.3"
crossterm = "0.29.0"
crossbeam-channel = "0.5.15"
crossbeam-queue = "0.3.12"
lazy_static = "1.5.0"

# Streaming and WebSocket dependencies
reqwest = { version = "0.12.22", features = ["json", "stream", "http3", "rustls-tls", "rustls-tls-native-roots", "rustls-tls-manual-roots", "gzip", "deflate", "brotli"] }
reqwest-eventsource = "0.6.0"
tokio-tungstenite = "0.27.0"
tracing = "0.1.41"

# Additional core dependencies
futures-core = "0.3.31"
schemars = "1.0.4"
async-stream = "0.3.6"
crossbeam-deque = "0.8.6"
anyhow = "1.0.98"
futures-executor = "0.3.31"

# Candle ML framework dependencies moved to fluent-ai-candle package

# ML/AI dependencies
image = { version = "0.25.6", optional = true }
hf-hub = { version = "0.4.3", features = ["tokio"], optional = true }
tokenizers = { version = "0.21.2", features = ["onig"], optional = true }
safetensors = { version = "0.6.0", optional = true }

# Optional acceleration dependencies
half = { version = "2.6.0", optional = true }
crossbeam-utils = "0.8.21"

[lib]
name = "fluent_ai"
path = "src/lib.rs"

# OS-specific acceleration dependencies
[target.'cfg(all(target_os = "linux", target_arch = "x86_64"))'.dependencies]
cudarc = { version = "0.16.6", optional = true, default-features = false, features = ["cublas", "cublaslt", "cudnn", "curand", "dynamic-linking", "f16", "std"] }
intel-mkl-src = { version = "0.8.1", optional = true }

[target.'cfg(all(target_os = "windows", target_arch = "x86_64"))'.dependencies]
cudarc = { version = "0.16.6", optional = true, default-features = false, features = ["cublas", "cublaslt", "cudnn", "curand", "dynamic-linking", "f16", "std"] }
intel-mkl-src = { version = "0.8.1", optional = true }

[target.'cfg(target_os = "macos")'.dependencies]
accelerate-src = { version = "0.3.2", optional = true }

[target.'cfg(all(target_os = "linux", target_arch = "x86_64"))'.build-dependencies]
bindgen_cuda = { version = "0.1.5", optional = true }

[target.'cfg(all(target_os = "windows", target_arch = "x86_64"))'.build-dependencies]
bindgen_cuda = { version = "0.1.5", optional = true }

[dev-dependencies]
tokio = { version = "1.46.1", features = ["macros", "rt-multi-thread"] }
