[package]
name = "fluent_ai_domain"
version = "0.1.0"
edition = "2024"

[features]
default = []
cylo = []

[dependencies]
serde = { version = "1.0.219", features = ["derive"] }
cyrup_sugars = { git = "https://github.com/cyrup-ai/cyrup-sugars", features = ["all"] }
thiserror = "2.0.12"
uuid = { version = "1.17.0", features = ["v4", "serde"] }
serde_json = "1.0.140"
tokio = { version = "1.46.1", features = ["full"] }
tokio-stream = "0.1.17"
futures = "0.3.31"
hashbrown = { version = "0.15.4", features = ["serde"] }
glob = "0.3.1"
fluent_ai_http3 = { path = "../http3" }
# fluent_ai_provider = { path = "../provider" }
base64 = "0.22.1"
tracing = "0.1.41"
termcolor = { path = "../termcolor" }
fluent_ai_memory = { path = "../memory", features = ["full-cognitive"] }
jwalk = "0.8.1"
rayon = "1.10.0"
gix = "0.73.0"
memmap2 = "0.9.5"
ignore = "0.4.23"
jemalloc-sys = "0.5.4"
ahash = "0.8.11"
chrono = { version = "0.4.39", features = ["serde"] }

# Ultra-high-performance dependencies for zero-allocation operations  
arrayvec = { version = "0.7.6", features = ["serde"] }
smallvec = { version = "2.0.0-alpha.11", features = ["serde"] }
crossbeam-deque = "0.8.6"
crossbeam-skiplist = "0.1.3"
crossbeam-utils = "0.8.21"
crossbeam-queue = "0.3.12"
wide = "0.7.33"
jemallocator = "0.5.4"
ropey = "2.0.0-alpha.3"
atomic-counter = "1.0.1"
arc-swap = "1.7.1"
once_cell = "1.21.3"
regex = "1.11"
parking_lot = "0.12.4"
dashmap = "6.0.1"
strsim = "0.11"
lz4 = "1.28.1"
html-escape = "0.2.13"

# Additional dependencies for memory migration
fastrand = "2.0.0"
num_cpus = "1.16.0"
bytes = "1.7.0"
serde_yaml = "0.9.34"
toml = "0.8.19"
rkyv = "0.8.10"
bincode = "2.0.1"
reqwest = { version = "0.12.22", features = ["json"] }
md5 = "0.8.0"

[dev-dependencies]
fluent_ai_provider = { path = "../provider" }
tracing-subscriber = "0.3.19"
jemalloc-sys = "0.5.4"
quanta = "0.12.6"
weak-table = "0.3.2"
fnv = "1.0.7"
hdrhistogram = "7.5.4"
html-escape = "0.2.13"
[lib]
name = "fluent_ai_domain"
path = "src/lib.rs"
