[package]
name = "fluent_ai_domain"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0.219", features = ["derive"] }
cyrup_sugars = { git = "https://github.com/cyrup-ai/cyrup-sugars", features = ["all"] }
thiserror = "2.0.12"
uuid = { version = "1.17.0", features = ["v4", "serde"] }
serde_json = "1.0.140"
tokio = { version = "1.46.1", features = ["full"] }
tokio-stream = "0.1.17"
futures = "0.3.31"
hashbrown = { version = "0.15.4", features = ["serde"] }
glob = "0.3.2"
fluent_ai_http3 = { path = "../http3" }
# fluent_ai_provider = { path = "../provider" }
base64 = "0.22.1"
cylo = { path = "../cylo" }
tracing = "0.1.41"
termcolor = { path = "../termcolor" }
fluent_ai_memory = { path = "../memory", features = ["full-cognitive"] }

[dev-dependencies]
serde = { version = "1.0.219", features = ["derive"] }
tokio = { version = "1.46.1", features = ["full", "rt-multi-thread", "macros"] }
fluent_ai_provider = { path = "../provider" }
crossbeam-queue = "0.3.12"
tracing-subscriber = "0.3.19"

# Ultra-high-performance dependencies for zero-allocation operations
arrayvec = "0.7.6"                  # Fixed-size arrays without heap allocation
smallvec = "2.0.0-alpha.11"         # Small vectors that avoid heap allocation
crossbeam-deque = "0.8.6"           # Lock-free work-stealing deque
crossbeam-skiplist = "0.1.3"        # Lock-free skip list
crossbeam-utils = "0.8.21"          # Lock-free utilities and atomic operations
rkyv = "0.8.10"                     # Zero-copy serialization
wide = "0.7.33"                     # SIMD vector operations
# packed_simd removed due to Rust 1.78+ compatibility issues - using wide crate instead
jemalloc-sys = "0.5.4"  # Custom allocator for vector operations
lz4 = "1.28.1"                      # Fast compression
jemallocator = "0.5.4"              # High-performance allocator backed by jemalloc
quanta = "0.12.6"                   # High-speed timing library
ropey = "2.0.0-alpha.3"             # Rope data structure for string building
circuit_breaker = "0.1.1"           # Circuit breaker pattern for error recovery
atomic-counter = "1.0.1"            # Atomic counters for statistics
memmap2 = "0.9.7"                   # Memory-mapped file operations
arc-swap = "1.7.1"                  # Lock-free atomic operations on Arc
weak-table = "0.3.2"                # Weak reference tables
parking_lot = "0.12.4"              # High-performance synchronization primitives
const-str = "0.6.3"                 # Compile-time string operations
fnv = "1.0.7"                       # Fowler–Noll–Vo hash function
hdrhistogram = "7.5.4"              # High dynamic range histogram
# config-rs = "0.14"                # Configuration management - temporarily disabled
once_cell = "1.21.3"                # Lazy static initialization
html-escape = "0.2.13"              # HTML escaping for code highlighting
dashmap = "6.0.1"                   # Concurrent hash map for caching

[lib]
name = "fluent_ai_domain"
path = "src/lib.rs"
