[package]
name = "fluent_ai_domain"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
cyrup_sugars = { git = "https://github.com/cyrup-ai/cyrup-sugars", rev = "cc262c4aa90493a6cf6ae4695b7dad28b0c1199d" }
thiserror = "2.0.12"
uuid = { version = "1.17.0", features = ["v4", "serde"] }
serde_json = "1.0"
tokio = { version = "1.46.1", features = ["full"] }
futures = "0.3"
hashbrown = { version = "0.15", features = ["serde"] }
glob = "0.3"
reqwest = { version = "0.12", features = ["json", "http3", "rustls-tls", "rustls-tls-native-roots"] }

[lib]
name = "fluent_ai_domain"
path = "src/lib.rs"
