[package]
name = "fluent_ai_async"
version = "0.1.0"
edition = "2024"
description = "Zero-allocation streaming primitives for the fluent-ai ecosystem"
license = "MIT OR Apache-2.0"
repository = "https://github.com/cyrup-ai/fluent-ai"

[dependencies]
cyrup_sugars = { git = "https://github.com/cyrup-ai/cyrup-sugars.git", features = ["all"] }
thiserror = "2"
crossbeam-channel = "0.5"
crossbeam-deque = "0.8"
crossbeam-queue = "0.3"
crossbeam-utils = { version = "0.8", features = ["std"] }
log = "0.4"


[lib]
path = "src/lib.rs"
name = "fluent_ai_async"

[dev-dependencies]
futures-util = "0.3"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
criterion = { version = "0.5", features = ["html_reports"] }

[[bench]]
name = "performance"
harness = false
