[package]
name = "fluent_ai_async"
version = "0.1.0"
edition = "2021"
description = "Zero-allocation streaming primitives for the fluent-ai ecosystem"
license = "MIT OR Apache-2.0"
repository = "https://github.com/cyrup-ai/fluent-ai"

[dependencies]
thiserror = "2.0.12"
serde = { version = "1.0", features = ["derive"] }
crossbeam-channel = "0.5"
crossbeam-queue = "0.3"
futures-util = "0.3"
fluent-ai-workspace-hack = { path = "../../workspace-hack" }

[features]
default = []
