[package]
name = "fluent_ai_candle"
version = "0.1.0"
edition = "2021"

# Examples temporarily disabled until all Candle domain types are implemented
# [[example]]
# name = "architecture_example"
# path = "examples/architecture_example.rs"



[dependencies]
# CRITICAL: NEVER ADD DEPENDENCY ON ./packages/domain or ./packages/fluent-ai
# fluent-ai-candle MUST remain completely standalone and independent
# ONLY ALLOWED fluent-ai dependencies: fluent-ai-async and fluent_ai_http3
fluent_ai_async = { path = "../async-stream" }
fluent-ai-simd = { path = "../simd" }
fluent-ai-workspace-hack = { path = "../../workspace-hack" }
cyrup_sugars = { git = "https://github.com/cyrup-ai/cyrup-sugars", branch = "main", package = "cyrup_sugars", features = ["all"] }
fluent_ai_http3 = { path = "../http3" }

# — DSP / NN (base dependencies - no acceleration features) —
candle-core = { git = "https://github.com/huggingface/candle", branch = "main", default-features = false }
candle-nn = { git = "https://github.com/huggingface/candle", branch = "main", default-features = false }
candle-transformers = { git = "https://github.com/huggingface/candle", branch = "main", default-features = false }
# — Optional acceleration dependencies —
half = { version = "2.6.0", optional = true }


# Platform-specific acceleration dependencies
cudarc = { version = "0.17.0", optional = true, default-features = false, features = [
    "cublas",
    "cublaslt",
    "cudnn",
    "curand",
    "dynamic-linking",
    "f16",
    "std",
] }
metal = { version = "0.32.0", optional = true }
bindgen_cuda = { version = "0.1.5", optional = true }
candle-kernels = { git = "https://github.com/huggingface/candle", branch = "main", optional = true }
candle-metal-kernels = { git = "https://github.com/huggingface/candle", branch = "main", optional = true }

# — audio / resampling —
# rubato is in workspace-hack
# rustfft is in workspace-hack
hound = "3.5.1"
symphonia = { version = "0.5.4", features = ["all"], optional = true }

# Core dependencies
serde = { version = "1.0.219", features = ["derive"] }
thiserror = "2.0.12"
uuid = { version = "1.17.0", features = ["v4", "serde"] }
serde_json = "1.0.142"
log = "0.4.27"
hashbrown = { version = "0.15.4", features = ["serde"] }
glob = "0.3.2"
base64 = "0.22.1"
tracing = "0.1.41"
termcolor = { path = "../termcolor" }
jwalk = "0.8.1"
flume = "0.11.1"
rayon = "1.10.0"
gix = "0.73.0"
yyaml = { git = "https://github.com/cyrup-ai/yyaml", branch = "main"}
memmap2 = "0.9.7"
ignore = "0.4.23"
ahash = "0.8.12"
chrono = { version = "0.4.41", features = ["serde"] }

# Ultra-high-performance dependencies for zero-allocation operations
arrayvec = { version = "0.7.6", features = ["serde"] }
smallvec = { version = "2.0.0-alpha.11", features = ["serde"] }
crossbeam-deque = "0.8.6"
crossbeam-skiplist = "0.1.3"
crossbeam-utils = "0.8.21"
crossbeam-queue = "0.3.12"
crossbeam-channel = "0.5.15"
crossbeam = "0.8.4"
cache-padded = "1.3.0"

wide = "0.7.33"
futures-util = { version = "0.3.31", default-features = false, features = ["std"] }
lazy_static = "1.5.0"
ropey = "2.0.0-beta.1"
atomic-counter = "1.0.1"
arc-swap = "1.7.1"
once_cell = "1.21.3"
regex = "1.11.1"
parking_lot = "0.12.4"
dashmap = "6.1.0"
strsim = "0.11.1"
lz4 = "1.28.1"


# Additional dependencies for memory migration
fastrand = "2.3.0"
rand = "0.9.2"
rand_pcg = "0.9.0"
num_cpus = "1.17.0"
bytes = "1.10.1"
toml = "0.9.5"
rkyv = { version = "0.8.11", optional = true }
bincode = { version = "2.0.1", optional = true }
reqwest = { version = "0.12.22", features = ["json"] }
md5 = "0.8.0"
tokio = { version = "1.47.1", features = ["full"] }
tokio-stream = "0.1.17"
async-stream = "0.3.6"
clap = { version = "4.5.42", features = ["derive"] }

[dev-dependencies]
tracing-subscriber = "0.3.19"
jemalloc-sys = "0.5.4"
quanta = "0.12.6"
weak-table = "0.3.2"
fnv = "1.0.7"
hdrhistogram = "7.5.4"


[[bin]]
name = "candle-chat"
path = "src/main.rs"

[lib]
name = "fluent_ai_candle"
path = "src/lib.rs"

# GPU features temporarily disabled for warning fixes
[features]
# ───────────── default: metal acceleration enabled ─────────────
default = ["metal", "reqwest_unstable"]

# --- Developer conveniences (opt-in) -----------------------
dev = ["debug"] # ← enable with `--features dev`
debug = []                 # extra logging / assertions

# --- SIMD features ---
portable_simd = []
reqwest_unstable = []

# --- Candle backend features (required for all candle crates) -----
cuda = [
    "dep:cudarc",
    "dep:bindgen_cuda",
    "dep:candle-kernels",
    "candle-core/cuda",
    "candle-nn/cuda",
    "candle-transformers/cuda",
]
cudnn = ["cuda", "cudarc/cudnn"]
metal = [
    "dep:metal",
    "dep:candle-metal-kernels",
    "candle-core/metal",
    "candle-nn/metal",
    "candle-transformers/metal",
]
accelerate = [
    "dep:accelerate-src",
    "candle-core/accelerate",
    "candle-nn/accelerate",
    "candle-transformers/accelerate",
]
mkl = [
    "dep:intel-mkl-src",
    "candle-core/mkl",
    "candle-nn/mkl",
    "candle-transformers/mkl",
]

# OS-specific acceleration dependencies
[target.'cfg(all(target_os = "linux", target_arch = "x86_64"))'.dependencies]
intel-mkl-src = { version = "0.8.1", optional = true }

[target.'cfg(all(target_os = "windows", target_arch = "x86_64"))'.dependencies]
intel-mkl-src = { version = "0.8.1", optional = true }

[target.'cfg(target_os = "macos")'.dependencies]
accelerate-src = { version = "0.3.2", optional = true }



